export const API_URL = 'https://chala.com.vn';

export const actionConstants = {
  START_QUERY: 'START_QUERY',
  END_QUERY: 'END_QUERY',

  GET_QUAT_SUCCESS: 'GET_QUAT_SUCCESS',
  GET_QUAT_FAILURE: 'GET_QUAT_FAILURE',

  GET_GIAY_SUCCESS: 'GET_GIAY_SUCCESS',
  GET_GIAY_FAILURE: 'GET_GIAY_FAILURE',

  GET_TT_SUCCESS: 'GET_TT_SUCCESS',
  GET_TT_FAILURE: 'GET_TT_FAILURE',
};
