export const API_URL = 'https://chala.com.vn';

export const actionConstants = {
  START_QUERY: 'START_QUERY',
  END_QUERY: 'END_QUERY',

  QUERY_SP_SUCCESS: 'QUERY_SP_SUCCESS',
  QUERY_SP_FAILURE: 'QUERY_SP_FAILURE',

  GET_QUAT_SUCCESS: 'GET_QUAT_SUCCESS',
  GET_QUAT_FAILURE: 'GET_QUAT_FAILURE',

  GET_GIAY_SUCCESS: 'GET_GIAY_SUCCESS',
  GET_GIAY_FAILURE: 'GET_GIAY_FAILURE',

  GET_TT_SUCCESS: 'GET_TT_SUCCESS',
  GET_TT_FAILURE: 'GET_TT_FAILURE',

  FETCH_PRODUCT_CAT_SUCCESS: 'FETCH_PRODUCT_CAT_SUCCESS',
  FETCH_PRODUCT_CAT_FAILURE: 'FETCH_PRODUCT_CAT_FAILURE',

  GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST_SUCCESS',
  GET_PRODUCT_LIST_FAILURE: 'GET_PRODUCT_LIST_SUCCESS',

  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  RETRIEVE_CART_SUCCESS: 'RETRIEVE_CART_SUCCESS',
};
